appkantin/urls.py
import statistics
from django.conf import settings
from django.contrib import admin
from django.urls import path
from makanan import views as makananView

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',makananView.home,name='home'),
    path('makanan/<int:makanan_id>', makananView.detail,name='detail'),
    path("about/", makananView.about , name="about")
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

makanan/models.py
from django.db import models
from django.core.validators import RegexValidator

# Create your models here.

class Kantin(models.Model):
    nama = models.CharField(max_length=250)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}', message="min 8 digit")
    telpon = models.CharField(validators=[phone_regex], max_length = 15, blank=  True)

    def __str__(self):
        return self.nama

    def __unicode__(self):
        return self.nama

class Makanan(models.Model):
    nama = models.CharField(max_length=250)
    harga = models.IntegerField()
    gambar = models.ImageField(upload_to='makan/images')
    stok = models.IntegerField()
    kantin = models.ForeignKey(Kantin,on_delete=models.CASCADE)
    TERSEDIA = (
        ('0', 'Tidak Tersedia'),
        ('1', 'Tersedia')
    )
    tersedia = models.CharField(max_length=1,choices=TERSEDIA)

    def __str__(self):
        return self.nama

    def __unicode__(self):
        return self.nama

makanan/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Makanan,Kantin
from django.shortcuts import get_object_or_404
# Create your views here.
def home(request):

    # ngambil objek orm
    kantins = Kantin.objects.all()

    # requset 
    searchMakanan = request.GET.get('nama')
    searchKantin = request.GET.get('kantin_id')


    if searchMakanan:
        makanans = Makanan.objects.filter(nama__icontains=searchMakanan)
    elif searchKantin:
        makanans = Makanan.objects.filter(kantin = searchKantin)
    else:
        makanans = Makanan.objects.all()

    return render(request, 'home.html', {
        'searchMakanan':searchMakanan,
        'makanans' : makanans,
        'kantins' : kantins,
        'page' : 'about'
        })
    
def detail(request,makanan_id):
    makanan = get_object_or_404(Makanan,pk=makanan_id)
    return render(request,'detail.html',{
        'makanan' : makanan,
        'page' : 'about',
        'ketersediaan' : makanan
        })

def about(request):
    return render(request,'about.html', { 'page' : 'about' })

makanan/templates/about.html
{% extends 'base.html' %}
{% block content%}
    <h1>Halaman {{ page }}</h1>
{% endblock %}

makanan/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{{ page }}</title>
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
              crossorigin="anonymous"/>
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}"><img  style="width: 20px;" src="{% static 'images/open-book.png'%}" alt="">Kantin Kevin</a>
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'about' %}">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

makanan/templates/detail.html
{% extends 'base.html' %}
{% block content %}
    <p>
        <div class="col-sm-8 container d-flex align-items-center justify-content-center" style="width: 32rem;">
            <div class="card">
                <img alt="" class="card-img-top" src="{{ makanan.gambar.url }}" />
                <div class="card-body">
                    <h5 class="card-title fw-bold">{{ makanan.nama }}</h5>
                    <p class="card-text">Makanan {{ makanan.get_tersedia_display }} Sebanyak {{ makanan.stok }} di kantin {{ makanan.kantin }}<br/>Berharga : {{ makanan.harga }}</p>
                    <a href='#' onclick="history.back()">Back</a>
                </div>
            </div>
        </div>
    </p>
{% endblock content %}

makanan/templates/home.html
{% extends "base.html" %}
{% block content %}

    <br/>
    kategori: <a class="btn btn-primary" href="{% url 'home' %}">Semua</a>

    {% for kantin in kantins %}
        <a class="btn btn-primary" href="?kantin_id={{ kantin.id }}">{{ kantin.nama }}</a>
    {% endfor %}

    <form action="">
        <div class="mb-3">
            <label class="form-label">Cari Makanan:</label>
            <input type="text" name="nama" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
    </form>
    {% if searchMakanan %}
        Pencarian untuk <strong>{{ searchMakanan }}</strong>
    {% endif %}

    <br/>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for makanan in makanans %}
            <div class="card mx-3" style="width: 18rem;">
                <img src="{{ makanan.gambar.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ makanan.nama }}</h5>
                    <p class="card-text">Makanan Sebanyak {{ makanan.stok }} di {{ makanan.kantin }}</p>
                    <a href="{% url 'detail' makanan.id %}" class="btn btn-primary">See</a>
                </div>
            </div>                  
        {% endfor %}
    </div> 

{% endblock content %}

<!-- <br/>
kategori: <a class="btn btn-primary" href="{% url 'home' %}">Semua</a>

{% for category in categories %}
    <a class="btn btn-primary" href="?category_id={{ category.id }}">{{ category.name }}</a>
{% endfor %}

<form action="">
    <div class="mb-3">
        <label class="form-label">Cari Buku:</label>
        <input type="text" name="judul" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
</form>
{% if searchJudul %}
    Pencarian untuk <strong>{{ searchJudul }}</strong>
{% endif %}

<br/>
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for book in books %}
    <div class="col">
        <div class="card">
            <img alt="" class="card-img-top" src="{{ book.image.url }}"  />
            <div class="card-body">
                <h5 class="card-title fw-bold">{{ book.title }} | {{ book.author }} | {{ book.release_date|date:"d-m-Y" }}</h5>
                <p class="card-text">
                    {{ book.description }}
                    <br/>
                    <br>
                    {{ book.isbn }} | {{ book.page_count }} | {{ book.category.name }}
                </p>
                <a class="btn btn-primary" href="{% url 'detail' book.id %}">Detail</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div> -->